server:
  port: 8080

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:3306/memorize_words
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    pool:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: false
        jdbc:
          batch_size: 25
          order_inserts: true
          order_updates: true

logging:
  level:
    com.memorizewords: INFO
    org.springframework.web: WARN
    org.hibernate: WARN
  file:
    name: logs/memorize-words-prod.log
  logback:
    rollingpolicy:
      max-file-size: 50MB
      max-history: 30

# Production-specific CORS
cors:
  allowed-origins: ${FRONTEND_URL}