server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: memorize-words
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/memorize_words?useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: false
  sql:
    init:
      mode: never

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
      probes:
        enabled: true
    metrics:
      enabled: true
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    tags:
      application: memorize-words
    distribution:
      percentiles-histogram:
        http.server.requests: true
        service.method.execution: true
        repository.query.execution: true
      percentiles:
        http.server.requests: 0.5, 0.95, 0.99
        service.method.execution: 0.5, 0.95, 0.99
    web:
      server:
        request:
          autotime:
            enabled: true
            percentiles: 0.5, 0.95, 0.99

logging:
  level:
    com.memorizewords: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# CORS configuration for frontend integration
cors:
  allowed-origins: http://localhost:3000,http://localhost:5173
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Performance monitoring configuration
monitoring:
  enabled: true
  alerting:
    enabled: true
    slow-query-threshold-ms: 1000
    slow-api-threshold-ms: 500
    high-memory-threshold-percent: 85
    critical-memory-threshold-percent: 90
  metrics:
    collection-interval-ms: 60000
    report-interval-ms: 300000
  database:
    connection-pool-monitoring: true
    slow-query-monitoring: true
  cache:
    monitoring: true
    hit-ratio-tracking: true